const {chromium}=require('playwright');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],writes=[];
 page.on('pageerror',e=>errors.push(e.message));
 const project={id:'project1',version:1,name:'Website',description:'',timezone:'Europe/Berlin',policy:[],archived:false};
 const agent={id:'agent1',version:1,name:'Recherche-Agent',client_id:'client1',projects:['project1'],scopes:['todo:read','todo:write'],revoked_at:null,last_activity:null};
 await page.route('http://localhost/**',route=>{
  const url=new URL(route.request().url());
  if(url.pathname==='/api'){
   const req=route.request().postDataJSON();if(req.mode==='write'){writes.push(req);return route.fulfill({json:{id:'new'}});}
   const data={projects:[project],tasks:{items:[],next_offset:null,total:0},task:{task:{id:'new',project_id:'project1',title:'Neu',status:'ready',priority:3,risk:1,effort:2,capabilities:['drive'],skill_ids:[],dependencies:[],tags:[]},subtasks:[],plans:[],reviews:[],comments:[],artifacts:[]},skills:[],capabilities:[{id:'drive',version:3,name:'Google Drive',description:'Dateien lesen'}],settings:{views:[],agents:[agent],policy:[],policy_hash:'hash'}};
   return route.fulfill({json:data[req.action]||{}});
  }
  const file=url.pathname==='/'?'includes/todo/views/app.php':'html/todo.mopoliti.de'+url.pathname;
  return route.fulfill({body:fs.readFileSync(file,'utf8').replace(/<\?=.*?\?>/g,'test'),contentType:url.pathname.endsWith('.css')?'text/css':url.pathname.endsWith('.js')?'application/javascript':'text/html'});
 });
 await page.goto('http://localhost/');
 await page.locator('[data-project="project1"]').waitFor();
 assert.equal(await page.locator('[data-page="projects"] + #project-shortcuts').count(),1);
 assert.equal(await page.locator('.project-shortcuts .add-project span').textContent(),'＋');
 assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).overflowY),'scroll');
 await page.locator('.new-task').click();
 const dialog=page.locator('#editor');
 assert(await dialog.evaluate(e=>e.classList.contains('task-editor')));
 assert.equal(await dialog.locator('[name="timezone"]').count(),0);
 assert.equal(await dialog.locator('input[type="date"]').count(),2);
 assert.equal(await dialog.locator('input[type="radio"]').count(),15);
 assert.match(await dialog.locator('.rating legend').first().textContent(),/5 = höchste/);
 assert(await dialog.locator('.rating').first().locator('input[value="5"] + span .level-5').count());
 assert(await dialog.evaluate(e=>e.scrollHeight<=e.clientHeight),'Desktop dialog scrolls');
 await page.screenshot({path:require('path').join(process.env.TODO_UI_OUTPUT||require('os').tmpdir(),'todo-editor-desktop.png')});
 await dialog.locator('.task-policy>summary').click();
 await dialog.locator('[data-policy-add]').click();
 await dialog.locator('[data-policy-key="effect"]').selectOption('deny');
 assert.equal(JSON.parse(await dialog.locator('[name="policy"]').inputValue())[0].effect,'deny');
 await dialog.locator('.policy-builder>details>summary').click();
 const policy=[{action:'external',effect:'approval',risk_min:3,agent:'a',project:'project1',capability:'drive',priority_max:2}];
 await dialog.locator('[name="policy"]').fill(JSON.stringify(policy));
 assert.equal(await dialog.locator('[data-policy-key="risk_min"]').inputValue(),'3');
 await dialog.locator('[data-policy-key="risk_min"]').selectOption('4');
 assert.deepEqual(JSON.parse(await dialog.locator('[name="policy"]').inputValue()),[{...policy[0],risk_min:4}]);
 await dialog.locator('[data-policy-remove]').click();
 assert.equal(await dialog.locator('[name="policy"]').inputValue(),'[]');
 await page.keyboard.press('Escape');
 await page.locator('[data-page="integrations"]').click();
 await page.locator('#toolbar [data-command="new-capability"]').click();
 assert.equal(await dialog.locator('[name="id"]').count(),0);
 await dialog.locator('[name="name"]').fill('Drive');await dialog.locator('[name="description"]').fill('Dateien lesen');
 await dialog.locator('[type="submit"]').click();
 await dialog.waitFor({state:'hidden'});
 assert.deepEqual(writes[0].input.name,'Drive');assert.equal(writes[0].input.description,'Dateien lesen');assert(!('id' in writes[0].input));
 await page.locator('[data-edit-capability="drive"]').click();
 assert.equal(await dialog.locator('[name="name"]').inputValue(),'Google Drive');assert.equal(await dialog.locator('[name="description"]').inputValue(),'Dateien lesen');
 await dialog.locator('[name="name"]').fill('Drive Ablage');await dialog.locator('[name="description"]').fill('Dateien lesen und ablegen');
 await dialog.locator('[type="submit"]').click();
 await dialog.waitFor({state:'hidden'});
 const capabilityWrite=writes.filter(w=>w.action==='capability_save').at(-1);
 assert.deepEqual(capabilityWrite.input,{id:'drive',expected_version:3,name:'Drive Ablage',description:'Dateien lesen und ablegen',idempotency_key:capabilityWrite.input.idempotency_key});
 await page.locator('[data-page="skills"]').click();
 await page.locator('[data-command="new-skill"]').click();
 assert.match(await dialog.textContent(),/Der Slug verbindet die Versionen/);
 assert.equal(await dialog.locator('[name="project_id"] option').first().textContent(),'Keinem Projekt zuordnen – projektübergreifend');
 assert.equal(await dialog.locator('[name="capabilities"] option').first().textContent(),'Google Drive');
 await dialog.locator('[name="name"]').fill('Recherche');await dialog.locator('[name="slug"]').fill('recherche');await dialog.locator('[name="content"]').fill('Quellen prüfen.');
 await dialog.locator('[name="project_id"]').selectOption('');await dialog.locator('[name="capabilities"]').selectOption('drive');
 await dialog.locator('[type="submit"]').click();await dialog.waitFor({state:'hidden'});
 const skillWrite=writes.find(w=>w.action==='skill_save');
 assert.equal(skillWrite.input.project_id,null);assert.deepEqual(skillWrite.input.capabilities,['drive']);
 await page.locator('[data-page="settings"]').click();
 await page.locator('[data-edit-agent="agent1"]').click();
 await dialog.locator('[name="name"]').fill('Analyse-Agent');
 await dialog.locator('[name="scopes"][value="todo:write"]').uncheck();
 await dialog.locator('[type="submit"]').click();
 await dialog.waitFor({state:'hidden'});
 const agentWrite=writes.find(w=>w.action==='agent_update');
 assert.equal(agentWrite.input.name,'Analyse-Agent');assert.deepEqual(agentWrite.input.projects,['project1']);assert.deepEqual(agentWrite.input.scopes,['todo:read']);
 await page.locator('[data-page="tasks"]').click();
 await page.locator('[data-view="board"]').click();
 assert.equal(await page.locator('.board-column').count(),8);
 assert.deepEqual(await page.locator('.board-column').evaluateAll(columns=>columns.map(column=>column.dataset.statuses)),['draft','ready','user_working waiting_user','agent_working','waiting_external','review','done','cancelled']);
 assert.match(await page.locator('.board-column').nth(2).textContent(),/^Deine Eingabe · 0/);
 assert(await page.locator('.board-column').first().evaluate(e=>e.getBoundingClientRect().bottom>=innerHeight-32),'Empty board should reach viewport bottom');
 await page.locator('#page-title select').selectOption('project1');
 assert.equal(await page.locator('#page-title select').inputValue(),'project1');
 await page.locator('[data-view="list"]').click();
 await page.evaluate(()=>{const base={project_id:'project1',tags:[],due_at:null};state.tasks=[{...base,id:'done',title:'Fertig',status:'done',start_at:Date.now()/1000+86400},{...base,id:'future',title:'Später',status:'ready',start_at:Date.now()/1000+86400},{...base,id:'open',title:'Jetzt',status:'ready',start_at:Date.now()/1000-1}];renderTasks();});
 assert.deepEqual(await page.locator('#content .task-row').evaluateAll(rows=>rows.map(r=>r.dataset.task)),['open','future','done']);
 for(const draft of [false,true]){
  await page.locator('.new-task').click();
  await dialog.locator('[name="title"]').fill('Neue Aufgabe');
  await dialog.locator(draft?'#save-draft':'button.primary[type="submit"]').click();
  await dialog.waitFor({state:'hidden'});
  assert.equal(writes.filter(w=>w.action==='task_create').at(-1).input.status,draft?'draft':'ready');
 }
 assert.match(await page.locator('.detail-meta').textContent(),/Google Drive/);
 assert.equal(await page.locator('.detail-meta .score').count(),3);
 assert.equal(await page.locator('.detail-status .recurrence').count(),1);
 assert.equal(await page.locator('#comment-form select').count(),0);
 await page.locator('#comment-form textarea').fill('Mein Kommentar');
 await page.locator('#comment-form button').click();
 await page.waitForFunction(()=>!document.querySelector('#comment-form button').disabled);
 assert.equal(writes.find(w=>w.action==='comment').input.type,'general');
 await page.locator('[data-command="close-detail"]').click();
 await page.setViewportSize({width:390,height:844});
 await page.locator('.page-heading [data-command="new-task"]').click();
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal overflow');
 assert(await dialog.evaluate(e=>e.scrollWidth<=e.clientWidth),'Mobile dialog horizontal overflow');
 await page.screenshot({path:require('path').join(process.env.TODO_UI_OUTPUT||require('os').tmpdir(),'todo-editor-mobile.png')});
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: navigation, dialog layout, date fields, ratings, policy round-trip, capability creation and editing, mobile overflow, JavaScript errors');
})().catch(e=>{console.error(e);process.exit(1);});
